### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by comio** [filebot/plex-agents#1]
Hi,

I'm having the following trace dump during directory scanning:
```

Aug 31, 2019 15:45:55.953 [0x7f14cf492740] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Movies/FileBot Xattr Movie Scanner.py", line 17, in Scan
    attr = xattr_metadata(file)
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Common/filebot.py", line 36, in xattr_metadata
    value = getxattr(file, 'net.filebot.metadata')
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Common/filebot.py", line 12, in getxattr
    value = xattr.getxattr(file, key)
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Common/xattr.py", line 48, in getxattr
    n = getxattr_impl(file, name, buffer)
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Common/xattr.py", line 28, in getxattr_impl
    return libc.getxattr(fsencode(file), fsencode('user.'+name), buffer, sizeof(buffer))
  File "/home/plex/Library/Application Support/Plex Media Server/Scanners/Common/xattr.py", line 44, in fsencode
    return file.encode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 50: ordinal not in range(128)
Aug 31, 2019 15:45:55.956 [0x7f14cf492740] ERROR - We got an error scanning in /media/overlay/Multimedia/Plex/Movies

```

Any Idea?

Thanks.

**Comment by rednoah** [comment]
What `OS` are you using? Sounds like the system encoding is not set correctly.

What does `uname -a` and `printenv` say?

**Comment by rednoah** [comment]
Maybe fixed with https://github.com/filebot/plex-agents/commit/1f16e5b76b0dce107f0aaf098d620dca5354bc5f

**Comment by rednoah** [comment]
Note that the underlying issue is `locale` not being set correctly. This is often the case on bare-bones Linux devices.

You'll encounter file system encoding issues with not just `python`, but also `java`, `ruby`, and all sorts of runtimes or programs since they all (correctly so) inherit the file system encoding from your environment.

Correctly setting `LANG` and `LC_ALL` is highly recommended:
```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

**Comment by comio** [comment]
Hi @rednoah,

sorry for the late answer.
These are my environment:
```

gentoobox ~ $ uname -a
Linux gentoobox 5.2.11-gentoo #1 SMP Fri Aug 30 08:13:38 CEST 2019 x86_64 Intel(R) Pentium(R) CPU N3700 @ 1.60GHz GenuineIntel GNU/Linux
comio@gentoobox ~ $ printenv 
...
LANG="it_IT.utf-8"
...

```
No LC_ALL is defined. I will add to my environment.
ciao

luigi
